spring.application.name=deliciassantana

spring.datasource.url=jdbc:mysql://localhost:3306/deliciassantana
spring.datasource.username=root
spring.datasource.password=Ra1812112@

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

lanchonete.whatsapp.numero=557582911913

# chave secreta usada para assinar o JWT — troque por uma string longa e aleatória sua
jwt.secret=18121121221118Ra18121121221118Ra
# tempo de expiração do token em milissegundos (aqui: 24 horas)
jwt.expiration=86400000
